export default{
    routes:[
        {
            path:'/',
            name:'Home',
            component:()=>import('@/views/Home')
        },
        {
            path:'/login',
            name:'Login',
            component:()=>import('@/views/Login')
        },
        {
            path:'/reg',
            name:'Reg',
            component:()=>import('@/views/Reg')
        },
        {
            path:'/channelNews/:id',
            name:'ChannelNews',
            component:()=>import('@/views/ChannelNews')
        },
        {
            path:'*',
            component:()=>import('@/views/NotFound')
        }
    ],
    mode:'history'
}